### ISSUE TITLE
how to translate contact track into readable contact matrix?

### ISSUE THREAD

**Issue by junmeiW** [tanaylab/schic2#1]
Hi, 
I've translated contact maps into genomic coordinates [according to this](https://github.com/tanaylab/schic2#translating-contact-maps-into-genomic-coordinates), and I found that the contact file was  like :

chrom1 | start1 | end1 | chrom2 | start2 | end2 | scell.nextera.1CDES_p1_C10 | intervalID
-- | -- | -- | -- | -- | -- | -- | --
chr1 | 3087908 | 3087909 | chr1 | 3417913 | 3417914 | 2 | 1
chr1 | 3348423 | 3348424 | chr1 | 3437289 | 3437290 | 2 | 1
chr1 | 3364316 | 3364317 | chr1 | 3364317 | 3364318 | 1 | 1
chr1 | 3364316 | 3364317 | chr1 | 3659874 | 3659875 | 2 | 1
chr1 | 3405087 | 3405088 | chr1 | 3405086 | 3405087 | 1 | 1
chr1 | 3405087 | 3405088 | chr1 | 3414410 | 3414411 | 2 | 1
chr1 | 3414410 | 3414411 | chr1 | 3404976 | 3404977 | 1 | 1
chr1 | 3414410 | 3414411 | chr1 | 3405087 | 3405088 | 2 | 1
chr1 | 3417913 | 3417914 | chr1 | 3087908 | 3087909 | 2 | 1
chr1 | 3437289 | 3437290 | chr1 | 3348423 | 3348424 | 2 | 1

the column ```end = start+1```,  I'm wondering the column ```scell.nextera.1CDES_p1_C10 ``` sometimes equals 2,  what does this indicates?

Looking forward to your reply!

Thank you!

**Comment by yaniv-el** [comment]
Hi,

Apologies for the late response. 
The 7th column (which will have the same name as the expression passed to gextract, which in this case is the track name) is the contact count after removing amplification duplicates. Most of the times the count will be 1, but not always, as there is a chance to capture the exact same contact more than once in cells with more than a single copy of a chromosome (diploids and haploids/diploids in S/G2), and also due to technical noise whice is reduced but not removed perfectly. 

Note that in our single cell analysis we disregard the contact count (effectively trimming the counts to 1), and these counts are only considered when pooling single cells to bulk-like Hi-C profiles.

Yaniv
